config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show]

  resources :carts, only: [:create]
  resources :orders, only: [:create]

  resources :artists, only: [:index, :show, :new, :create] do
    resources :songs, only: [:index, :new, :create, :edit, :update]
  end

  resources :songs, only: [:index, :show]

  namespace :admin do
    resources :categories, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates_presence_of :name

  has_many :songs
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(contents)
    @contents = contents || Hash.new(0)
  end

  def total_count
    @contents.values.sum
  end

  def add_song(id)
    @contents[id] += 1
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_songs
  has_many :songs, through: :order_songs
end

app/models/order_song.rb
class OrderSong < ApplicationRecord
  belongs_to :order
  belongs_to :song
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs

  validates_presence_of :name  
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs

  validates_presence_of :title

  validates :length, presence: true, numericality: {
    greater_than_or_equal_to: 0
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders

  has_secure_password

  validates :username, uniqueness: true, presence: true
  validates_presence_of :password, require: true

  enum role: ['default', 'admin']
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  # here
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_cart

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def require_admin
    render file: '/public/404' unless current_admin?
  end

  def set_cart
    @cart ||= Cart.new(session[:cart])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to "/artists/#{@artist.id}"
    else
      render :new
    end
  end

  private

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def create
    song = Song.find(params[:song_id])
    song_id_str = song.id.to_s
    @cart.add_song(song_id_str)
    session[:cart] = @cart.contents
    quantity = session[:cart][song_id_str]
    flash[:success] = "You now have #{pluralize(quantity, "copy")} of #{song.title} in your cart."
    redirect_to songs_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    user = User.find(session[:user_id])
    order = user.orders.create!
    @cart.contents.each do |song_id, quantity|
      order.order_songs.create(song_id: song_id , quantity: quantity)
    end
    @cart.contents.clear
    redirect_to songs_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @song = Song.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to song_path(@song)
    else
      render :new
    end
  end

  def edit
    @artist = Artist.find(params[:artist_id])
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])

    @song.title = params[:song][:title]
    @song.length = params[:song][:length]
    @song.play_count = params[:song][:play_count]

    if @song.save
      redirect_to song_path(@song)
    else
      render :edit
    end
  end

  private

  def song_params
    params.require(:song).permit(:title, :length, :play_count)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>Admin Categories</h1>

app/views/artists/new.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h1> <%= @artist.name %> </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jukebox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
      <%= link_to 'Log Out', logout_path %>
    <% else %>
      <%= link_to 'Register as a User', new_user_path %>
      <%= link_to 'Log In', login_path %>
    <% end %>

    <p>Cart: <%= @cart.total_count %></p>
    <%= button_to "Create Order", orders_path %>

    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<% if @song.errors %>
<ul id="errors">
  <% @song.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= form_for [@artist, @song] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :length %>
  <%= f.number_field :length %>

  <%= f.label :play_count %>
  <%= f.number_field :play_count %>

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h2>Edit Song</h2>

<%= render partial: 'form' %>

app/views/songs/index.html.erb
<%= flash.each do |type, message| %>
  <%= content_tag :div, message, class: type %>
<% end %>

<h1>All Songs</h1>

<% @songs.each do |song| %>
  <section id="song-<%= song.id %>">
    <h3><%=  link_to song.title, song_path(song), class: 'here' %></h3>
    <p>Play count: <%= song.play_count %></p>
    <p>Length: <%= song.length %></p>
    <%= button_to "Add Song", carts_path(song_id: song.id) %>
  </section>
<% end %>

app/views/songs/new.html.erb
<h2>Edit Song</h2>

<%= render partial: 'form' %>

app/views/songs/show.html.erb
<section id="song-<%= @song.id %>">
  <h1><%= @song.title %></h1>
  <p>length: <%= @song.length %></p>
  <p>play count: <%= @song.play_count %></p>
</section>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

<p><%= f.label :username %>
<%= f.text_field :username %></p>

<p><%= f.label :password %>
<%= f.password_field :password %></p>

<p><%= f.submit %>

<% end %>

app/views/users/show.html.erb
<p>Welcome, <%= current_user.username %>!</p>